environment: dev
resourceGroupName: dev-resource-group
appServicePlanName: dev-app-service-plan
appServiceName: dev-app-service
keyVaultName: dev-key-vault
appInsightsName: dev-app-insights
storageAccountName: devstorageaccount
storageAccountSku: Standard_LRS
appServicePlanSku: F1
appServiceTier: Free
appServicePlanSize: F1
appServicePlanCapacity: 1
keyVaultFamily: A
keyVaultKind: standard
accessPolicies:
  - objectId: 3df8d3af-5b86-4dd9-8f34-39e9e4b1d258 // This is the object ID for DevOps SG
  - objectId: 2b0fb052-6c5e-4c6c-ba2d-465ec16dbf87 // This is the object ID for Architects SG
location: eastus
tags:
  environment: dev
  project: simplewebsite2